services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test1234
    volumes:
      - .:/app

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # Neo4j web interface
      - "7687:7687"  # Bolt protocol
    environment:
      NEO4J_AUTH: "neo4j/test1234"
